version: '3.9'

services:
  workspace:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - GIT_USER=user
        - GIT_EMAIL=user@123.de

    volumes:
      - ./.ssh:/home/user/.ssh:ro
      - ./.env:/home/user/.env:ro
      - C:\Users\user\Desktop\projects:/home/user/projects